apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wzweng5ie-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wzweng5ie-go 
  name: wzweng5ie-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wzweng5ie-go 
