apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wzweng5ie-go 
  janus-idp.io/tekton: wzweng5ie-go
  backstage.io/kubernetes-id: wzweng5ie-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wzweng5ie-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml