apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: wzweng5ie-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/rhtap-qe-go:7eafd02f517d9ff67f8a213ef513964e53fb4e38@sha256:f64561cae4a23aa058cf372ef5e5c8502a64424a8cc2b4a7661defedbc5b1201
          name: container-image
